"""Ablation 6 — what imperfect perception costs.

The arrival gate stopped being an oracle. A witness used to ask TraCI where a
vehicle really was; it now endorses a claim only if its own observation agrees.
That makes a lane lie catchable by sensing rather than by consulting the
simulator — and it also means an honest vehicle can be refused, because the
witness misread it. This figure is about the price of that trade.

Sigma is not a free parameter. Each arm's confusion matrix is the one implied by
a Gaussian lateral error of that sigma against the junction's real 3.2 m lane
width, generated by scenarios/fourway/generate_perception_matrices.py and
checked in as perception_matrices.csv. The x axis is therefore a physical
quantity, not a knob: sigma=0.25 m is already sub-millimetre in its effect
(7.8e-11 off-diagonal), while sigma=2.0 m puts 21% of observations on the wrong
approach.

Three panels, in the order the damage propagates:

  certificates -> commits -> crossings

Sensor error first costs echoes, which costs certificates; only once
certificates are scarce enough to threaten f+1 does it cost a commit; and only a
lost commit costs a crossing.

Panel 1 is points, not a curve. Only replicas that assemble a certificate emit
Cert_Collection_Duration, so a cell can hold one or two observations rather than
one per vehicle, and a mean over two very different values is an artefact rather
than a central tendency -- see docs/ablations.md section 6 for the measured
samples. Repetitions are what turn it into a curve. Reading them together is what distinguishes
"degraded but safe" from "broken" — a run that commits nothing is safe and
useless, and a single commit-rate panel cannot tell you which you are looking
at.

What is deliberately NOT here: any measure of attack success. This study varies
sensor quality with every replica honest. Mixing a Byzantine arm in would
confound "the witness misread an honest car" with "the witness correctly refused
a liar", and those are the two outcomes the whole gate exists to separate.
Ablation 2 covers the adversarial case.
"""
from ..io import discover
from ..metrics import aggregate
from .. import style

NAME = "ab6_perception"
TITLE = "Imperfect perception: certificate, consensus and crossing cost vs sensor error"
STUDY = 6
SUBPLOTS = (1, 3)
FIGSIZE = (15.0, 5.0)

_ARM = "perception"

# k carries sigma in centimetres, because the log-name grammar has an integer
# there. Labelled in metres, which is the unit the parameter is actually in.
def _sigma_m(k: int) -> float:
    return k / 100.0


_PANELS = (
    ("Certificate collection", "seconds to assemble f+1 echoes",
     aggregate.cert_collection),
    ("Consensus", "% of runs committing", aggregate.commit_rate),
    ("Crossings", "vehicles cleared", aggregate.cleared),
)


def load(runs):
    ks = discover.ks(runs, arm=_ARM, study=STUDY)
    if not ks:
        return {}
    ns = discover.ns(runs, arm=_ARM, study=STUDY)
    if not ns:
        return {}
    # One series per vehicle count, swept over sigma. Keyed by N so a partially
    # run study still plots the counts it has rather than nothing.
    data = {}
    for n in ns:
        cells = []
        for k in ks:
            recs = discover.cell(runs, STUDY, _ARM, k=k, n=n)
            if recs:
                cells.append((_sigma_m(k), recs))
        if cells:
            data[n] = cells
    return data


def build(data, axes):
    ns = sorted(data)
    for ax, (title, ylabel, metric) in zip(axes.flat, _PANELS):
        for i, n in enumerate(ns):
            cells = data[n]
            xs = [sigma for sigma, _ in cells]
            stats = [metric(recs) for _, recs in cells]
            spec = style.ordered(i, len(ns), f"N={n}")
            style.errorbar(ax, xs, stats, spec)
        style.finish(ax, title=title, xlabel="lateral observation sigma (m)",
                     ylabel=ylabel, legend=len(ns) > 1)

    fig = axes.flat[0].get_figure()
    fig.suptitle(
        "Ablation 6 — perception error is absorbed by certificate collection "
        "before it reaches consensus",
        fontsize=12, color=style.INK_PRIMARY)
